/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace emInterfaces
{
  /// <summary>
  /// Standard types of waveform that the signal generator can produce
  /// </summary>
  public enum emLogEventType
  {
    /// <summary>
    /// Undefined, here for consistency
    /// </summary>
    emNULL = 0,
    CONFIG = 1,
    emERROR = 2,
    MISC = 3,
    COMMAND = 4,
    RESPONSE = 5,
    DONOTLOG = 6,
    DISPLAYASMESSAGEBOX = 7,
  }
}
