/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace emInterfaces
{
  /// <summary>
  /// The EM controller plays back a set of operations. Think of it as a multitrack audio editing software. Logcally, each PIN has its own queue of operations. Each of these operations has a start and end time, and a set of parameters to define what each pin will be doing during that time. Operations are one of a few basic types:
  /// </summary>
  public enum emSequenceOperationType
  {
    /// <summary>
    /// Undefined, but here just to make sure there is a null type
    /// </summary>
    emNULL = 0,
    /// <summary>
    /// Play back from buffer
    /// </summary>
    ARBITRARY = 1,
    /// <summary>
    /// record from a pin and store into a buffer.
    /// </summary>
    RECORD = 2,
    /// <summary>
    /// does nothing for a period of time. Used to pad operations
    /// </summary>
    WAIT = 3,
    /// <summary>
    /// Use the waveFormType for signal generation
    /// </summary>
    PREDEFINED = 4,
    /// <summary>
    /// Outputs a value of amplitude
    /// </summary>
    CONSTANT = 5,
    /// <summary>
    /// Outputs a Binary value on based on amplitude. Amplitude=0, output 0, else 1
    /// </summary>
    DIGITAL = 6,
  }
}
