all:
	g++ -std=c++11 -lthrift -I /usr/include/libusb-1.0/ emEvolvableMotherboard.cpp shared_constants.cpp emDataApi.cpp  NascenseAPI_v01d_types.cpp NascenseAPI_v01d_constants.cpp emMotherboard.cpp  ga.cpp usb.c -lusb-1.0 -lgomp -o evo
