/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef NascenseAPI_v01e_CONSTANTS_H
#define NascenseAPI_v01e_CONSTANTS_H

#include "NascenseAPI_v01e_types.h"

namespace emInterfaces {

class NascenseAPI_v01eConstants {
 public:
  NascenseAPI_v01eConstants();

};

extern const NascenseAPI_v01eConstants g_NascenseAPI_v01e_constants;

} // namespace

#endif
