/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef NascenseAPI_v01d_CONSTANTS_H
#define NascenseAPI_v01d_CONSTANTS_H

#include "NascenseAPI_v01d_types.h"

namespace emInterfaces {

class NascenseAPI_v01dConstants {
 public:
  NascenseAPI_v01dConstants();

};

extern const NascenseAPI_v01dConstants g_NascenseAPI_v01d_constants;

} // namespace

#endif
