/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef NascenseAPI_v01c_CONSTANTS_H
#define NascenseAPI_v01c_CONSTANTS_H

#include "NascenseAPI_v01c_types.h"

namespace emInterfaces {

class NascenseAPI_v01cConstants {
 public:
  NascenseAPI_v01cConstants();

};

extern const NascenseAPI_v01cConstants g_NascenseAPI_v01c_constants;

} // namespace

#endif
