/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace emInterfaces
{
  public enum emExceptionType
  {
    /// <summary>
    /// Serious error, needs handling or recovery
    /// </summary>
    CRITICAL = 0,
    /// <summary>
    /// Treat as a warning
    /// </summary>
    NONFATAL = 1,
  }
}
