/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace emInterfaces
{

  /// <summary>
  /// Structure to encapsulate log setting
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class emLogServerSettings : TBase
  {
    private string _logServer;
    private string _experimentName;

    /// <summary>
    /// URL for log server
    /// </summary>
    public string LogServer
    {
      get
      {
        return _logServer;
      }
      set
      {
        __isset.logServer = true;
        this._logServer = value;
      }
    }

    /// <summary>
    /// Name of experiment
    /// </summary>
    public string ExperimentName
    {
      get
      {
        return _experimentName;
      }
      set
      {
        __isset.experimentName = true;
        this._experimentName = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool logServer;
      public bool experimentName;
    }

    public emLogServerSettings() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              LogServer = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              ExperimentName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("emLogServerSettings");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (LogServer != null && __isset.logServer) {
        field.Name = "logServer";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(LogServer);
        oprot.WriteFieldEnd();
      }
      if (ExperimentName != null && __isset.experimentName) {
        field.Name = "experimentName";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(ExperimentName);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("emLogServerSettings(");
      sb.Append("LogServer: ");
      sb.Append(LogServer);
      sb.Append(",ExperimentName: ");
      sb.Append(ExperimentName);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
