/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "NascenseAPI_v01e_constants.h"

namespace emInterfaces {

const NascenseAPI_v01eConstants g_NascenseAPI_v01e_constants;

NascenseAPI_v01eConstants::NascenseAPI_v01eConstants() {
}

} // namespace

