/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "NascenseAPI_v01d_constants.h"

namespace emInterfaces {

const NascenseAPI_v01dConstants g_NascenseAPI_v01d_constants;

NascenseAPI_v01dConstants::NascenseAPI_v01dConstants() {
}

} // namespace

